FOSSRIT/fossrit.github.io

- _config.yml
- _includes/layout/seo-meta.html
There was more remains from RITlug than I realized. I made a first attempt at bringing some of the SEO-specific content up-to-date to help our brand visibility and not get our site confused with RITlug.
> Add var for Twitter, update more SEO changes to FOSS@MAGIC

- _config.yml
- _includes/layout/seo-meta.html
This pull request does two things:
1. Sets the SEO keywords in `seo-meta.html` with variable in `_config.yml`
2. Adds some suggested keywords to help optimize the site's visibility in search engines
I'm tagging @ct-martin and @desnudopenguino for a review if either of them have time. Eventually, once I complete #19, the need for reviewing smaller changes like this will go away.
> Set SEO keywords with variable in site config (closes #26)

- .github/CONTRIBUTING.md
- README.md
- start_devel_env.sh
This pull request adds new documentation to explain how to create a development environment to build and preview the fossrit.github.io website locally.
I tagged a few people for review because I'd like feedback to improve these instructions. By following the below instructions, you should be able to run a local development instance of the fossrit.github.io website. It should only take executing a script. If you have Docker already installed, it should "Just Work™".
Could anyone actually try this and let me know if it works easily for them? Is anything confusing or could it be better explained?
> Add development environment instructions (closes #19)

- events/_posts/2018-11-06-election-night-hackathon.md
- get-involved.md
Expands some of the lists towards the bottom of the _Get involved_ page. Also includes some revisions suggested by @itprofjacobs.
> Minor content revisions to Get Involved page

- announcements/_posts/2019-05-21-cfp-announcement.md
Embolden conference title in running text
Fixes #50
> Correct "Humanitarian and Civics" typo

- events/_posts/2019-10-26-the-future-is-open.md
This commit makes three changes to The Future is Open 2019 schedule:
* Adds a talk title for @Nolski's talk
* Corrects the time for "Open source in educational games" talk
* Shifts install fest up to other sessions starting at 12pm
> Future is Open: Update schedule, fix typos

- events/_posts/2019-10-26-the-future-is-open.md
This commit makes a tiny change of wording the "Alumni Panel" to the
"Alum Panel". Because:
1) There is an alumna on the panel.
2) "Alums" is a gender-neutral version of the word.
Sooooo, making the shift here.
> FIO: "Alumni Panel" -> "Alum Panel" for inclusivity

- _config.yml
- events/_posts/2019-11-05-election-night-hackathon.md
> Fix foss hours dow 2019

- events/_posts/2011-04-23-linux-installfest.md
Another historical grab, this time featuring Rochester's own @cprofitt
leading a 2011 Linux installfest at RIT. Also came from @mansam's
FOSSbox archive, written by @decause.
http://www.samlucidi.com/fossbox/event-decause-linux-installfest.html
I wonder if pictures exist anywhere for this one.
> events: Add 2011 Linux installfest by @cprofitt from @decause

- events/_posts/2011-05-19-breakfast-send-off.md
I stumbled on this one and thought it was a little piece of FOSSbox
history worth archiving. It was a breakfast send-off for @jlew when he
moved on from RIT organized by @decause.
http://www.samlucidi.com/fossbox/event-decause-fossrit-breakfast-sendoff.html
> events: Add 2011 @jlew breakfast send-off from @decause

- README.md
This commit adds a note to the README that this website does not have
full feature parity with the RITlug site, and links to issue #87 where
there is more specific details on the differences.
Closes #87.
> Note lack of feature parity with RITlug site (closes #87)

- events/_posts/2011-07-12-syracuse-student-sandbox-hackathon.md
This was an event we did in collaboration with Syracuse University in
2011:
http://www.samlucidi.com/fossbox/event-decause-fossrit--su-student-sandbox-hackathon.html
> events: Add FOSS + Syracuse hackathon from @decause

- events/_posts/2013-07-23-white-house-champions-change.md
This was an accidental find, but it was too good to not include on our
new website. I stumbled across the only running archive I know of for
the old FOSSbox website:
http://www.samlucidi.com/fossbox/articles/decause/magic-centers-fossrit-program-sends-students-to-white-house-champions-of-change-event.html
In a best effort to preserve that data, I've moved it over into our new
site and decided to publish it under the _Events_ page.
I only wish I had pictures to include here.
cc: @decause @jenneh @ramstush @DAWacker @itprofjacobs @mansam
> Add "White House Champions of Change" event, from @decause

- events/_posts/2010-11-04-election-night-hackathon.md
This commit makes a handful of adjustments to the Election Night
Hackathon 2010 event post. Most notably it fixes a typoed URL. I also
changed some formatting to improve readability and added an internal
link to help out some with site S.E.O.
> events: Fix URL, adjust formatting for ENH 2010

- projects/_posts/2019-12-31-tigeros.html
This commit updates TigerOS for the FOSS@MAGIC Projects part of the
website. I added @gen1e and @jibby0 as contributors, updated the GitHub
button to point to the new GitLab, and updated the year from 2018 to
2019. As far as I know, the last major activity on TigerOS was last
semester.
cc: @tjzabel
> projects: Update TigerOS year and project repositories

- announcements/_posts/2019-04-16-imagine-rit.md
- announcements/index.html
- projects/_posts/2019-12-31-tigeros.html
CI is introduced in #114. While putting that PR together, it found several valid things on our site that are actually broken or unexpected. This PR fixes them, so when #114 is merged, it should pass and also deploy our site to production.
---
d51cd9ccc5f852aae51789b089880887634f2cda — :bookmark_tabs: **announcements: Fix 404 for FOSS Minor curriculum**
Previously in an Imagine RIT announcement, I linked to the PDF of the
FOSS courses to talk about work that came from the IGME-585 course. RIT
did the ol' switcheroo on us, so this points that link to the new place
for FOSS minor curriculum.
---
4856857c9b8ef6afbe046182ce06146e6b87dceb —  :link: **announcements: Fix broken URL**
For some reason, this link was broken. Might have been old cruft from
the RITlug website circa 2015.
--- …
> Fix various HTML errors/broken links to make CI pass

- about.md
Similar to commit 3710bcf216d77703bdc46346e119c51e309c595d. The old link
to the PDF was dropped on RIT's website, this updates the pointer to the
current web home of the FOSS Minor.
Also, I added a small note for the Future is Open conference too on our
_About_ page.
> about: Fix link to FOSS Minor curriculum

- .travis.yml
- README.md
- _config.yml
This commits adds Travis CI support for FOSSRIT/fossrit.github.io. It
builds the site with Jekyll, checks for HTML errors and broken links
with `html-proofer`, and if successful and run on `master`, it deploys
the latest build of the site from Travis.
I used the official Jekyll docs to set up testing, although there were
several things missing that took me a long time to figure out how to get
that part working:
https://jekyllrb.com/docs/continuous-integration/travis-ci/
Never forget, `bundler exec`. :grimacing:
It is worth noting a few things are disabled in `html-proofer` that
realistically should be enabled. We _should_ check for alt tags, we
should _not_ have to ignore `/projects/` but we do because they are
appended with `.html` extensions for some reason, unlike the rest of the
site. …
> Add Travis CI gated deployments (closes #44)

- calendar.html
This simplifies `calendar.html` by removing the logic to strip the
`RITlug: ` prefix from the summary field. This is true of the RITlug
site, but is not true of the FOSS@RIT website. No functionality changes
in this commit, it only reduces complexity.
> calendar: Remove summary prefix logic

- .travis.yml
This adjusts the Travis config to build the site and push the static
site content in `_site/` to the `gh-pages` branch. Once this is enabled,
I'll enable the `gh-pages` branch in the repo settings and set up branch
protections.
Closes #119.
> ci: Build and deploy to gh-pages branch (closes #119)

- .travis.yml
In favor of simplicity, this PR undoes the Travis CI deployment
pipeline. While all changes will _still_ be tested and required to pass
before new changes can be merged, Travis is no longer responsible for
pushing the built site source to the GitHub Pages environment.
The purpose of this change is to drop the `src` branch, revert `master`
to the default branch, and use a single branch for building and
deploying the site source. Since we are not using any advanced
functionality of Jekyll yet that warrants us to build outside of the
github-pages Gem, I think it is better to keep this simple for those who
will come after me.
Since this will bring us back to a fairly simple, single-branch workflow
with `master`, I no longer see the need in documenting the Runbook CI
deployment pipeline …
> ci: Revert Travis deploy pipeline

- librecorps.md
Minor change to link out the work-in-progress LibreCorps website. There
isn't much there now, but there is definitely some content of use. It
will only grow over the next couple of weeks.
Also I want to test the new automatic deploy preview for PRs I enabled
with Netlify.
> librecorps: Add link to Resources site

- librecorps.md
Added a few suggested edits by @itprofjacobs:
1. Our work with UNICEF Innovation Fund: Specifically describing the
mentorship and collaboration with portfolio teams
2. Resources: Add roadmap template and self-evaluation rubric
3. Past LibreCorps student contributors: Brief shout-out for our past
and current students who worked on RIT LibreCorps initiatives
> librecorps: Add suggested SJ edits

- _config.yml
- robots.txt
This is a Search Engine Optimization (S.E.O.) tweak. A sitemap is a file
for search engines that creates a digital map of all the content
published on a website. Using a plugin, Jekyll will create one for
fossrit.github.io and put it at the root of the domain. Using a
`robots.txt` is a more explicit way we tell other search engines that a
sitemap is present and to go and use it for indexing.
> config: Generate a sitemap and highlight it in robots.txt

- Rakefile
- _data/tabs.yml
- _includes/layout/header.html
> Add dropdown to navbar

- _includes/layout/seo-meta.html
This commit adds a new `<meta>` tag that appears in the `<head>` of
every page. It verifies that admin access to `fossrit.github.io` is
correctly given in the Google Search Console interface.
My intention is to use this tool to submit the sitemap to Google and
also promote specific pages on our site in Google.
> seo-meta: Add meta tag for Google Search Console verification

- _data/tabs.yml
- open-rit.md
This commit adds a new page to the FOSSRIT website,
https://fossrit.github.io/open-rit/, that describes the on-going work to
explore an Open Source Programs Office at RIT. This is based on copytext
sent to me from @itprofjacobs with minor tweaks of my own.
Needs to be merged by 2020-04-23 @ 1:50pm US/Eastern.
Closes #146.
> Add new "Open@RIT" page to track ongoing work (closes #146)

- Rakefile
- _data/tabs.yml
This adds an outlink to the FOSSRIT People page. This better integrates
the work done by @kennedy for the FOSSRIT Profiles page into our web
presence. It does not close FOSSRIT/people#72 though. We need to link
back to this website from the People page in order to close that issue.
> Add FOSSRIT People/Profiles link to site navbar

- meetings-meetups/_posts/2020-01-16-foss-hours.md
- meetings-meetups/_posts/2020-03-26-virtual-foss-hours.md
- robots.txt
Google Search Console threw an error when it tried to crawl this URL:
https://fossrit.github.io/meetings-meetups/2020/03/26/virtual-foss-hours/
Why it is a problem doesn't make much sense to me, since I wasn't
blocking it in our `robots.txt`, but Google seems to think it is
blocked. However, when users see this content, they are actually looking
at fossrit.github.io/calendar/ and not the above URL, so we actually
don't need Google or any search engine crawling those pages.
So, this adds Front Matter that explicitly excludes calendar events in
the sitemap and also adds a `Disallow` rule to tell search engines not
to crawl that directory.
This should fix the error reported in the Google Search Console.
> calendar: Do not include calendar pages in sitemap

- meetings-meetups/_posts/2020-05-07-summer-foss-hours.md
This commit adds a new calendar event for Summer 2020 (specifically 7
May to 13 August). Once every other week, the FOSS Family will gather
together to say hi until we see each other again (hopefully) in Fall
semester.
Closes #150.
> calendar: Add Virtual FOSS Hours for Summer 2020 (closes #150)

- _data/footer/rit.yml
- about.md
This commit adds a footer link for the FOSS@RIT Runbook and also briefly
explains it on the About page. This is intended to give the Runbook
better site visibility and also help search engines discover it.
Closes #143.
> about/footer: Add link to FOSS@RIT Runbook (closes #143)

- announcements/_posts/2019-02-20-open-source-roundtable-gdc.md
Unfortunately this page was not saved in the Internet Archive, so I am
just dropping the URL since it is a 404 now, and the value of trying to
fix it is very low. It was a link to a schedule of the conference.
> ci: Drop a 404 link purged on G.D.C. website

- announcements/_posts/2022-07-21-open-works-in-academia-summit
- events/_posts/2010-11-04-election-night-hackathon.md
Adding an announcement about the summit to the webpage.
The event is findable by searching for the exact terms, and the Open Works
definition has almost zero search engine juice. I'm hoping some meaningful
cross-linking will began to help with that, and things to tweet about too.
> Announcement for Open Works in Academia summit

- Gemfile
- Gemfile.lock
Found this when trying to build the website locally.
When running the build.sh file, I ran into an error message:
```
cannot load such file -- webrick (LoadError)
```
Apparently on the latest version of Jekyll, we need to add this package, or serving will no longer work (but building the site works just fine).  See: https://jekyllrb.com/news/2022/03/27/jekyll-3-9-2-released/
This pull simply adds the webrick package so the build.sh file is able to serve again with the latest version of jekyll.
> Add Webrick to Gemfile

- feeds/latest.xml
I noticed the Announcements RSS feed used RITlug's description, and not FOSS@RIT's description.
With this update, the <description> tag will now use the one in the config.yml file.  It will look something like this:
```
<description>
Center of gravity for Free and Open Source Software at the Rochester Institute of Technology. Learn about open source activities and academia at RIT.
</description>
```
> Updated annoucement feed to use the site's description, and not RITlug's
