FOSSRIT/fossrit.github.io

index.html
Fixes #6 
I'm game to get the email link fixed next once I wrap my head around the fedorahosted link, and also to look into matrix 1-click, but for now this is not nothing.
=> adding an IRC icon and link

README.md
* expand scope of purpose around FOSS hours to include location, but in many fewer words :-)
closes #10
=> * correct editing mistake

announcements/_posts/2018-11-13-welcome.md, announcements/index.html
This adds a first announcement to the website.
=> Add first announcement as test

about.md, get-involved.md, index.html, librecorps.md
=> Add new page for LibreCorps (from @itprofjacobs content)

index.html
This was easier than I initially realized. I removed the comments around the older code. Theoretically, it should "just work". However, until I get a chance to test, I want to make sure this change looks right. If it looks good enough, I'll merge it and we'll let it hit the production site.
@ct-martin @desnudopenguino Tagging both of you again because I know you have some experience here. If you could take a quick peek and let me know if this looks right, that would be great! :+1:
=> Show announcements on home page again (closes #27)

start_devel_env.sh
This is a beginning for #19. This adds a script that theoretically anyone can use to spin up a new development environment of the website that continually updates as changes are made. Sometimes I hit weird issues, but sometimes it works. More info in #19.
=> Add script to create development environment with a container

_config.yml, about.md
This pull request pushes some content changes to the _About_ page from @itprofjacobs. I tested these changes locally and verified this is a working change.
=> Update About page with @itprofjacobs edits

librecorps.md
Some more minor revisions from @itprofjacobs. This time to the _LibreCorps_ page.
=> Minor revisions to LibreCorps page by @itprofjacobs

announcements/_posts/2019-02-20-open-source-roundtable-gdc.md
I reviewed this together in person with @itprofjacobs. Going to merge this and get it published and publicized. :clapper:
=> Add new announcement about IGDA DGC Roundtable from @itprofjacobs

announcements/_posts/2019-05-21-cfp-announcement.md
Authored the announcement of the Call for Proposals, and I was hoping to publish it today.
=> CfP announcement

announcements/_posts/2019-08-19-foss-hours-2191.md
Going to merge this one through to start spreading the word across the interwebs.
=> Announcement: FOSS Hours for Fall 2019 semester

announcements/_posts/2019-10-03-rochester-maker-faire.md
Let's get the word out for the Maker Faire! :construction_worker_woman: :construction: :construction_worker_man:
=> announcements: Add RMF call for participation

events/_posts/2019-10-26-the-future-is-open.md
This is from the Eventbrite page; schedule can be updated once that's released. Also, code for the photos is there but commented and after the event they can be added to the frontmatter.
=> Create event for The Future is Open 2019

get-involved.md
Fixes https://github.com/FOSSRIT/fossrit.github.io/issues/55
=> Replace URL for FOSS Minor from old and busted to new and working.

events/_posts/2019-10-26-the-future-is-open.md
This commit takes the in-person schedule maps drawn up with
@itprofjacobs and @whenbellstoll and digitizes it on the site. Based off
of @ct-martin's original changes.
=> Publish final draft of The Future is Open 2019 schedule

events/_posts/2019-10-26-the-future-is-open.md
=> Fixed Spelling of Name

events/_posts/2019-10-26-the-future-is-open.md
=> Fix syntax error

events/_posts/2019-10-26-the-future-is-open.md
Takes advantage of width of desktop, standardizes styling, styling bug fixes (including #61), emphasises headers:
Mobile still looks the same:
=> Nicer schedule

events/_posts/2019-10-26-the-future-is-open.md
Quick change from a phone call with @itprofjacobs.
=> FIO: Add Nando Ellis to alum panel

events/_posts/2019-10-26-the-future-is-open.md
This commit adds a new surprise speaker we got near the last minute.
This adds his name to the Speaker page as well as a new row for a Track
D. It doesn't look pretty as it is now, but maybe @ct-martin can take a
look and see if there is a better way of laying out the fourth track in
the schedule.
=> FIO: Add "Tracking the impact of zoo conservation" from Tom Snyder

events/_posts/2019-10-26-the-future-is-open.md
@jwflory Please don't add a Track E; 12 doesn't cleanly divide by 5. Also, we're running out of horizontal space.
<details>
<summary>Desktop</summary>
</details>
<details>
<summary>Tablet</summary>
</details>
<details>
<summary>Mobile</summary>
</details>
=> FIO: Put Track D in row

events/_posts/2019-10-26-the-future-is-open.md
* Alphabetize
* Add missing speakers
* Update some bios
<details>
<summary>Screenshot</summary>
</details>
cc @jwflory @Nolski
=> FIO: Update speakers

events/_posts/2019-10-26-the-future-is-open.md
=> FIO: Final Schedule

css/styles.css
This PR is a mirror of the [RITlug PR](https://github.com/RITlug/ritlug.github.io/pull/231) to improve the footer contrasting.
=> Improve footer contrast

events/_posts/2019-10-26-the-future-is-open.md
No screenshot b/c did in-browser; should display photos
=> FIO: Uncomment photo gallery

events/_posts/2019-11-05-election-night-hackathon.md
Could use a second set of eyes on this to check for places where I didn't update things that should be changed from 2018 to 2019. 
Needs location and times.
Also, I recycled the images from last year. An image from the poster might be appropriate to swap in here.
Since time is short I'm pushing this through as is. Reviews and patches welcome.
=> Rough-in event for 2019 Election Night Hackathon based on 2018 post.

librecorps.md
This makes some language tweaks and changes to LibreCorps website
content based on IRL feedback from @itprofjacobs.
=> librecorps: Make edits from @itprofjacobs feedback

announcements/_posts/2019-12-17-spring-2020-volunteers.md
This commit adds a new call for volunteers for the Spring 2020 semester,
and possibly beyond. It links out to a Google Form I created to start
soliciting interest for getting people involved next semester.
=> announcement: Add call for volunteers in Spring 2020

events/_posts/2013-09-21-software-freedom-day.md
Another grab from the old FOSSbox website:
http://www.samlucidi.com/fossbox/event-decause-software-freedom-day-2013.html
Wish I had pictures. :cry:
cc: @decause @mansam @itprofjacobs
=> events: Add Software Freedom Day 2013 from @decause @mansam

events/_posts/2012-12-01-random-hacks-kindness-hackathon.md
Another historical grab:
http://www.samlucidi.com/fossbox/articles/decause/random-hacks-of-kindness-global-hackathon-rochester.html
https://www.eventbrite.com/e/rhok-global-december-2012-rochester-ny-usa-tickets-4175149986#
I'm straight up history-tripping here. cc: @decause @mansam
@itprofjacobs
=> events: Add RHoK 2012 hackathon from @decause @mansam

events/_posts/2013-04-17-walter-bender-book-signing.md
Walter Bender came to RIT? That's so cool. I wonder if @ritjoe knew
about this:
http://www.samlucidi.com/fossbox/event-decause-walter-bender-book-signing.html
cc: @itprofjacobs
=> events: Add Walter Bending book signing from @decause @mansam

events/_posts/2011-10-22-csh-olpc-fundraiser-tournament.md
Another one that I thought was worth saving:
http://www.samlucidi.com/fossbox/event-decause-csh-charity-fundraiser-for-olpc--super-smash-bros-64-tournament.html
https://www.facebook.com/events/187149931359484/
=> events: Add 2011 CSH OLPC Smash fundraiser from @decause

events/_posts/2011-03-09-foss-spring-opportunities.md
This archived event isn't particularly noteworthy, but I thought it was
a cool idea. Perhaps it is something future generations of students
could consider organizing. So, I decided to archive this one to serve as
future inspiration for those who come after me:
http://www.samlucidi.com/fossbox/event-decause-fossrit-spring-opportunities-meeting.html
=> events: Add 2011 Spring open house from @decause

announcements/_posts/2020-03-11-call-for-imagine-2020-projects.md
This makes an open call for Imagine RIT 2020 projects and includes a
Google Form for people to submit project proposals to. The form exists
in the FOSS@MAGIC Shared Drive.
cc: @whenbellstoll
=> announcement: Add call for Imagine RIT 2020 projects

announcements/_posts/2020-03-11-call-for-imagine-2020-projects.md
Poor timing on a call for projects. But what can you do? #COVID19
=> announcements: Imagine RIT 2020 is canceled

announcements/_posts/2020-03-18-virtual-foss-hours.md
We're going virtual. :sunglasses: This just makes it official. #COVID19
=> announcement: Virtual FOSS Hours!

_config.yml, index.html
This is a slight refresh of the main two columns of our home page. It
also updates some of our S.E.O. data in our config for better
discoverability with our current efforts.
=> index: Refresh "Do/Discuss" columns for 2020

announcements/_posts/2020-04-28-summer-foss-hours.md
Keep the FOSS rolling. We'll meet about twice each month for the rest of
the summer.
=> announcement: Add Summer FOSS Hours announcement with links

announcements/_posts/2019-02-20-open-source-roundtable-gdc.md, meetings-meetups/_posts/2020-06-05-calls-for-justice.md
"The RIT community is invited to come together to reflect on the
struggles that we are all facing during these painful times."
https://www.rit.edu/news/rit-will-host-calls-justice-vigil-zoom-friday
=> calendar: Add RIT Calls for Justice virtual vigil

_config.yml, meetings-meetups/_posts/2020-08-27-foss-hours.md
(re: SJ email)
* Updates time/place in config
* Creates recurring event
Notes:
* Did not properly test; should be fine b/c it's minimal changes and I don't have Jekyll installed but please double-check
* We should add a mechanism to allow links instead of places. Note that this will also require changing the "[date], [time] _in_ [place]" grammer to allow "on" or "at" instead of "in"
* Keep it minimal too b/c we could also add a link to the RIT maps for the room in the future once things go in-person again
Rough (from memory, untested) code for link change:
```
{% if site.meeting-link %}<a href="{{ site.meeting-link }}">{{ site.meeting-place }}</a>{% else %}{{ site.meeting-place }}{% endif %}
```
```
{% if site.meeting-link %}![{{ site.meeting-place }}]({{ site.meeting-link }}){% else %}{{ …
```
=> Fall FOSS Hours

_includes/layout/head.html, _layouts/default.html, css/styles.css
Fixes #45 
Please test; I don't have Jekyll installed but this is fairly minimal so it should work
Updates Bootstrap as well
=> Fix images overflowing on mobile

index.html
=> update matrix link to point to the libera.chat room instead

README.md, _config.yml, history.txt, open-rit.md
=> Update Open @ RIT Page and FOSS hours times

projects/_posts/2020-03-01-teleirc.md
a draft pull request for switching the TeleIRC link to libera once it gets mograted
=> update TeleIRC link to libera
